security:
    providers:

        #in_memory:
            #memory:
                #users:
                    #user1:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin1: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        our_db_provider:
            entity:
                class: App\Entity\Utilisateur
                property: utilLogin

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            form_login:
                login_path: /security/formConnection
                check_path: /security/checkConnection
                default_target_path: /accueil
            logout:
                path:   /security/logout
                target: /accueil

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADHERANT, ROLE_PRODUCTEUR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\Utilisateur:
            algorithm: bcrypt